GET http://localhost:3000/messages

###
GET http://localhost:3000/messages/643d911ab2e015a12f85d5a2

###
POST http://localhost:3000/messages
Content-Type: application/json

{
    "recipientEmail": "joebiden@gmail.com",
    "recipientText": "I am inviting you in the white house."
}



###
DELETE http://localhost:3000/messages/64385ec70737fa714c490661


###
PATCH  http://localhost:3000/messages/643eecd1a5e0e11f315cc41a
Content-Type: application/json

{
    "recipientEmail": "barakobama@yahoo.com"   
}
